a = input('digite algo ')
print('o tipo primitivo desse valor é',type(a))
print(' so tem numeros ?',a.isnumeric())
print('é formado so por espaços? ',a.isspace())
print('é Alfabetico ?',a.isalpha())
print('é alfanumerico ?',a.isalnum())
print('so tem letras maiusculas ?',a.isupper())
print('so tem letras minusculas ?',a.islower())
print('esta capitalizado ? ',a.istitle())